# TooLoo documentation file.
# Details: https://github.com/masukomi/TooLoo
name="epub_cleaner"
short_description="strips watermarks from ePub docs."

description="""
Removes OceanOfPDF.com links from ePub documents,
and generates a new .epub file with the changes.

Eventually will remove other watermarks I encounter.
"""

# usage_command=""

fallback_usage="""
USAGE: epub_cleaner <path to epub>
"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/epub_cleaner"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"

# can this be included in exports like the static blog generation
exportable=true

tags=[ "epub"  ]
