# TooLoo documentation file.
# Details: https://github.com/masukomi/TooLoo
name="git-show-tag-message"
short_description="shows the message associated with a tag"

description="""
Shows the message associated with a tag and nothing else.
Excludes the signature and everything after it.

Assumes there will be a signature because what kind of
monster goes around not signing their tags. Do you WANT
to get hacked? Sheesh.
"""

# usage_command=""

fallback_usage="""
git show-tag-message <tag>
"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url=""
# where you can find the repo that contains this file
source_repo_url=""

# can this be included in exports like the static blog generation
exportable=true

tags=[ "git"  ]
