# TooLoo documentation file.
# Details: https://github.com/masukomi/TooLoo
name="git-changelog"
short_description="generates a changelog from tags"

description="""
Iterates over all the tags in a repo
and generates a changelog file in .org or .md format.
"""

# usage_command=""

fallback_usage="""
USAGE: git changelog [md|org]"
       if format isn't specified org-mode will be used
"""

# is this an executable, function, or ???
type="executable"
# what language is it written in?
language="bash"
# where you can find this specific file in source control
source_url="https://github.com/masukomi/masuconfigs/blob/master/bin/git-scripts/git-changelog"
# where you can find the repo that contains this file
source_repo_url="https://github.com/masukomi/masuconfigs"

# can this be included in exports like the static blog generation
exportable=true

tags=[ "git" ]
